# Generated by Django 4.1.3 on 2022-12-08 16:50

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [

        
        migrations.CreateModel(
            name='faculty_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email2', models.CharField(max_length=50, null=True)),
                ('f_name', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100, null=True)),
                ('l_date', models.DateField()),
                ('lab_num', models.CharField(max_length=100, null=True)),
                ('crs_sec', models.CharField(max_length=100, null=True)),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('fl_sig', models.TextField(max_length=10000, null=True)),
                ('l_stat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_passreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fwname', models.CharField(max_length=100)),
                ('fwempID', models.CharField(max_length=100, null=True)),
                ('fwIDtype', models.CharField(choices=[('GSFE', 'GSFE'), ('TUP EMAIL', 'TUP EMAIL'), ('MS TEAMS', 'MS TEAMS'), ('ERS ACCOUNT', 'ERS ACCOUNT'), ('NAS', 'NAS')], max_length=40)),
                ('fwemail', models.CharField(max_length=100, null=True)),
                ('fwstat', models.CharField(max_length=100, null=True)),
            ],
        ),
       
        migrations.CreateModel(
            name='faculty_wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gf_name', models.CharField(max_length=100)),
                ('g_dept', models.CharField(max_length=100, null=True)),
                ('g_des', models.CharField(max_length=100, null=True)),
                ('g_sys', models.CharField(max_length=100, null=True)),
                ('g_mac', models.CharField(max_length=100, null=True)),
                ('g_num', models.CharField(max_length=100, null=True)),
                ('g_email', models.CharField(max_length=100, null=True)),
                ('g_fac', models.CharField(max_length=100, null=True)),
                ('g_sig', models.TextField(max_length=10000, null=True)),
                ('g_datereq', models.DateField()),
                ('g_stat', models.CharField(max_length=100, null=True)),
            ],
        ),

        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgsfe', models.CharField(max_length=100)),
                ('lidno', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
       
        migrations.CreateModel(
            name='PassReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('emp_idno', models.CharField(max_length=50, null=True)),
                ('Account', models.CharField(choices=[('GSFE', 'GSFE'), ('TUP EMAIL', 'TUP EMAIL'), ('MS TEAMS', 'MS TEAMS'), ('ERS ACCOUNT', 'ERS ACCOUNT'), ('NAS', 'NAS')], max_length=100, null=True)),
                ('psstats', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sched_rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_name', models.CharField(max_length=100)),
                ('h_dept', models.CharField(max_length=100, null=True)),
                ('h_daterec', models.DateField()),
                ('hl_num', models.CharField(max_length=100, null=True)),
                ('h_csec', models.CharField(max_length=100, null=True)),
                ('hs_time', models.TimeField()),
                ('he_time', models.TimeField()),
                ('h_sig', models.TextField(max_length=10000, null=True)),
                ('h_stats', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gf_name2', models.CharField(max_length=100)),
                ('g_csec2', models.CharField(max_length=100, null=True)),
                ('g_snum2', models.CharField(max_length=100, null=True)),
                ('g_sem2', models.CharField(max_length=100, null=True)),
                ('g_or2', models.CharField(max_length=100, null=True)),
                ('g_num2', models.CharField(max_length=100, null=True)),
                ('g_email2', models.CharField(max_length=100, null=True)),
                ('g_add2', models.CharField(max_length=100, null=True)),
                ('gu_name2', models.CharField(max_length=100, null=True)),
                ('g_sig2', models.TextField(max_length=10000, null=True)),
                ('g_daterec2', models.DateField()),
                ('g_stats2', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gf_name1', models.CharField(max_length=100)),
                ('g_csec1', models.CharField(max_length=100, null=True)),
                ('g_snum1', models.CharField(max_length=100, null=True)),
                ('g_sem1', models.CharField(max_length=100, null=True)),
                ('g_or1', models.CharField(max_length=100, null=True)),
                ('g_sys1', models.CharField(max_length=100, null=True)),
                ('g_mac1', models.CharField(max_length=100, null=True)),
                ('g_num1', models.CharField(max_length=100, null=True)),
                ('g_email1', models.CharField(max_length=100, null=True)),
                ('g_add1', models.CharField(max_length=100, null=True)),
                ('g_sig1', models.TextField(max_length=10000, null=True)),
                ('g_daterec1', models.DateField()),
                ('g_stats1', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Personal_description', models.CharField(default='', max_length=40, null=True)),
                ('gsfe', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
