# Generated by Django 4.1.1 on 2022-10-05 05:16

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ff_name', models.CharField(max_length=50)),
                ('fm_name', models.CharField(max_length=50)),
                ('fl_name', models.CharField(max_length=50)),
                ('f_suffix', models.CharField(max_length=50, null=True)),
                ('f_emp', models.CharField(max_length=100)),
                ('f_datereq', models.DateField()),
                ('f_daterel', models.DateField()),
                ('f_gsis', models.CharField(max_length=100, null=True)),
                ('f_gsisp', models.CharField(max_length=100, null=True)),
                ('f_tin', models.CharField(max_length=100, null=True)),
                ('f_pagibig', models.CharField(max_length=100, null=True)),
                ('f_phil', models.CharField(max_length=100, null=True)),
                ('f_other', models.CharField(max_length=100, null=True)),
                ('f_cp', models.CharField(max_length=100, null=True)),
                ('f_num', models.CharField(max_length=100, null=True)),
                ('f_add', models.CharField(max_length=200, null=True)),
                ('f_signature', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('Password_data', models.CharField(default='', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usernamep', models.CharField(max_length=50)),
                ('pic', models.FileField(max_length=254, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Personal_description', models.CharField(choices=[('Faculty Member', 'Faculty Member'), ('UITC Staff', 'UITC Staff'), ('Student', 'Student')], max_length=40)),
                ('idno', models.CharField(max_length=20)),
                ('pic', models.FileField(max_length=254, upload_to='')),
                ('Status', models.CharField(default='On process', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
