# Generated by Django 4.0.4 on 2022-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_dateass',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_daterec1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_daterec2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_time1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_time2',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='ie_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='ie_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='is_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='is_time',
            field=models.TimeField(null=True),
        ),
    ]
