# Generated by Django 4.1.1 on 2022-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_reports',
            name='fstat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
