# Generated by Django 4.1.3 on 2022-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Schedule_l2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l2mon', models.TextField(max_length=100)),
                ('l2tue', models.TextField(max_length=100)),
                ('l2wed', models.TextField(max_length=100)),
                ('l2thurs', models.TextField(max_length=100)),
                ('l2fri', models.TextField(max_length=100)),
                ('l2sat', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_l3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l3mon', models.TextField(max_length=100)),
                ('l3tue', models.TextField(max_length=100)),
                ('l3wed', models.TextField(max_length=100)),
                ('l3thurs', models.TextField(max_length=100)),
                ('l3fri', models.TextField(max_length=100)),
                ('l3sat', models.TextField(max_length=100)),
            ],
        ),
    ]
