# Generated by Django 4.1.2 on 2022-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='i_quant',
            new_name='i_model',
        ),
        migrations.AddField(
            model_name='inventory',
            name='i_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='i_serial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
