# Generated by Django 4.1.1 on 2022-10-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register1',
            name='pic',
        ),
    ]
