# Generated by Django 4.1.2 on 2022-10-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrow_record',
        ),
        migrations.DeleteModel(
            name='maintain_record',
        ),
        migrations.DeleteModel(
            name='repmain_rec',
        ),
        migrations.DeleteModel(
            name='sched_rec',
        ),
        migrations.DeleteModel(
            name='student_internet',
        ),
        migrations.DeleteModel(
            name='student_wifi',
        ),
    ]
