# Generated by Django 4.1.1 on 2022-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='Personal_description',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='register1',
            name='gsfe',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
