# Generated by Django 4.1.2 on 2022-12-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_id',
            name='f_dept',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
