# Generated by Django 4.1.2 on 2022-11-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintain_record',
            name='i_sig4',
        ),
    ]
