# Generated by Django 4.0.4 on 2022-11-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='email5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
