# Generated by Django 4.1.1 on 2022-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passreset',
            name='psname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passreset',
            name='psstats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
