# Generated by Django 4.1.4 on 2022-12-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_faculty_id_maintain_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_reports',
            old_name='station',
            new_name='i_serv',
        ),
    ]
