# Generated by Django 4.1.3 on 2023-01-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_alter_maintain_record_i_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_record',
            name='i_sign',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
