# Generated by Django 4.1.2 on 2022-12-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_remove_maintain_record_i_sig4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('gsfe', models.EmailField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(max_length=65)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
