# Generated by Django 4.1.4 on 2022-12-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_alter_faculty_reports_i_dateass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_id',
            name='f_signature',
            field=models.ImageField(max_length=10000, upload_to=None),
        ),
        migrations.AlterField(
            model_name='faculty_lab',
            name='fl_sig',
            field=models.ImageField(max_length=1000, upload_to=None),
        ),
        migrations.AlterField(
            model_name='faculty_wifi',
            name='g_sig',
            field=models.ImageField(max_length=10000, upload_to=None),
        ),
    ]
