# Generated by Django 4.1.3 on 2022-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_borrow_record_faculty_borrow_faculty_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_equip', models.CharField(max_length=100, null=True)),
                ('i_model', models.CharField(max_length=100, null=True)),
                ('i_serial', models.CharField(max_length=100, null=True)),
                ('i_date', models.DateField()),
                ('i_stats', models.CharField(default='Available', max_length=100)),
            ],
        ),
    ]
