# Generated by Django 4.1.4 on 2022-12-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_record',
            name='i_sig5',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_borrow',
            name='fbsign',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_lab',
            name='fl_sig',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='fsign',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_sig',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_sig1',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_sig2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_reports',
            name='i_sig3',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_wifi',
            name='g_sig',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='maintain_record',
            name='i_sig5',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='sched_rec',
            name='h_sig',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='student_internet',
            name='g_sig2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='student_wifi',
            name='g_sig1',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
