# Generated by Django 4.0.1 on 2022-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_alter_register1_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_pic', models.TextField(max_length=10000, null=True)),
                ('email1', models.CharField(max_length=50, null=True)),
                ('ff_name', models.CharField(max_length=50)),
                ('fm_name', models.CharField(max_length=50, null=True)),
                ('fl_name', models.CharField(max_length=50)),
                ('f_suffix', models.CharField(max_length=50, null=True)),
                ('f_emp', models.CharField(max_length=100)),
                ('f_datereq', models.DateField(null=True)),
                ('f_daterel', models.DateField(null=True)),
                ('f_gsis', models.CharField(max_length=100, null=True)),
                ('f_gsisp', models.CharField(max_length=100, null=True)),
                ('f_tin', models.CharField(max_length=100, null=True)),
                ('f_pagibig', models.CharField(max_length=100, null=True)),
                ('f_phil', models.CharField(max_length=100, null=True)),
                ('f_other', models.CharField(max_length=100, null=True)),
                ('f_cp', models.CharField(max_length=100, null=True)),
                ('f_num', models.CharField(max_length=100, null=True)),
                ('f_add', models.CharField(max_length=200, null=True)),
                ('f_signature', models.TextField(max_length=10000, null=True)),
                ('f_stat', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
