# Generated by Django 4.1.2 on 2022-11-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_rename_i_quant_inventory_i_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_borrow',
            name='email4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty_id',
            name='email1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty_lab',
            name='email2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty_reports',
            name='email3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
