# Generated by Django 4.1.1 on 2022-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_faculty_reports_fstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_passreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fwname', models.CharField(max_length=100)),
                ('fwempID', models.CharField(max_length=100, null=True)),
                ('fwIDtype', models.CharField(choices=[('GSFE', 'GSFE'), ('TUP EMAIL', 'TUP EMAIL'), ('MS TEAMS', 'MS TEAMS'), ('ERS ACCOUNT', 'ERS ACCOUNT'), ('NAS', 'NAS')], max_length=40)),
                ('fwstat', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
