# Generated by Django 4.1.3 on 2022-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0002_schedule_l1_schedule_l2_schedule_l3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_l1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1mon', models.TextField(max_length=100)),
                ('l1tue', models.TextField(max_length=100)),
                ('l1wed', models.TextField(max_length=100)),
                ('l1thurs', models.TextField(max_length=100)),
                ('l1fri', models.TextField(max_length=100)),
                ('l1sat', models.TextField(max_length=100)),
            ],
        ),
    ]
