# Generated by Django 4.1.4 on 2023-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0003_alter_maintain_record_i_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lubnum', models.CharField(max_length=100)),
                ('lmon', models.CharField(max_length=100)),
                ('ltue', models.CharField(max_length=100)),
                ('lwed', models.CharField(max_length=100)),
                ('lthu', models.CharField(max_length=100)),
                ('lfri', models.CharField(max_length=100)),
                ('ldate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule_l1',
        ),
        migrations.DeleteModel(
            name='Schedule_l2',
        ),
        migrations.DeleteModel(
            name='Schedule_l3',
        ),
    ]
