# Generated by Django 4.1.2 on 2022-12-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0003_temp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp_User',
        ),
    ]
