# Generated by Django 4.1.3 on 2022-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0003_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='i_stats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
