# Generated by Django 4.1.3 on 2022-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0003_schedule_l1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_l1',
            old_name='l1thurs',
            new_name='l1thu',
        ),
    ]
