# Generated by Django 4.1.1 on 2022-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0003_uitc_borrow_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_record',
            name='i_sig5',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
