# Generated by Django 4.1.1 on 2022-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0004_maintain_record_i_sig5'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_passreset',
            name='fwemail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
