# Generated by Django 4.1.2 on 2022-10-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0004_borrow_record_faculty_wifi_maintain_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('emp_idno', models.CharField(max_length=50, null=True)),
                ('Account', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
