# Generated by Django 4.1.3 on 2022-12-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0004_rename_l1thurs_schedule_l1_l1thu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1fri',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1mon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1sat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1thu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1tue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule_l1',
            name='l1wed',
            field=models.CharField(max_length=100),
        ),
    ]
