# Generated by Django 4.0.4 on 2022-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0005_passreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passreset',
            name='Account',
            field=models.CharField(choices=[('GSFE', 'GSFE'), ('TUP EMAIL', 'TUP EMAIL'), ('MS TEAMS', 'MS TEAMS'), ('ERS ACCOUNT', 'ERS ACCOUNT'), ('NAS', 'NAS')], max_length=100, null=True),
        ),
    ]
