# Generated by Django 4.1.3 on 2022-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0005_alter_schedule_l1_l1fri_alter_schedule_l1_l1mon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_l1',
            name='l1sat',
        ),
    ]
