# Generated by Django 4.1.2 on 2022-11-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0005_faculty_passreset_fwemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UITC_borrow_record',
        ),
    ]
