# Generated by Django 4.1.2 on 2022-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0006_delete_uitc_borrow_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_quant', models.CharField(max_length=100, null=True)),
                ('i_equip', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
