# Generated by Django 4.0.1 on 2023-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0006_alter_schedule_lab_lfri_alter_schedule_lab_lmon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_id',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
    ]
