# Generated by Django 4.1.1 on 2022-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0006_alter_passreset_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_id',
            name='f_daterel',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty_id',
            name='f_datereq',
            field=models.DateField(null=True),
        ),
    ]
