# Generated by Django 4.1.3 on 2022-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0006_faculty_borrow_fbmodel_faculty_borrow_fbserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_borrow',
            name='fbequip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
