# Generated by Django 4.0.1 on 2023-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0007_faculty_id_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_wifi',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
    ]
