# Generated by Django 4.1.3 on 2022-12-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0007_faculty_borrow_fbequip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_borrow',
            name='fbequip',
        ),
    ]
