# Generated by Django 4.1.1 on 2022-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0007_alter_faculty_id_f_daterel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_id',
            name='fm_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
