# Generated by Django 4.1.2 on 2022-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0007_remove_schedule_l2_l2sat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_l3',
            name='l3sat',
        ),
    ]
