# Generated by Django 4.1.1 on 2022-10-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0008_alter_faculty_id_fm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('l_date', models.DateField()),
                ('lab_num', models.CharField(max_length=100)),
                ('crs_sec', models.CharField(max_length=100)),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('fl_sig', models.ImageField(upload_to=None)),
            ],
        ),
    ]
