# Generated by Django 4.1.3 on 2022-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0008_remove_faculty_borrow_fbequip'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='imodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrow_record',
            name='iserial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow_record',
            name='i_rdate5',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_record',
            name='i_remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
