# Generated by Django 4.0.1 on 2023-01-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0008_faculty_wifi_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_wifi',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
    ]
