# Generated by Django 4.1.3 on 2022-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0009_alter_register1_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_id',
            name='f_sign',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
