# Generated by Django 4.1.1 on 2022-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0009_faculty_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_wifi',
            old_name='g_stats',
            new_name='g_stat',
        ),
        migrations.AddField(
            model_name='faculty_id',
            name='f_stat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
