# Generated by Django 4.1.3 on 2022-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0009_borrow_record_imodel_borrow_record_iserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='i_user',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty_borrow',
            name='fbuser',
            field=models.CharField(default='Faculty Member', max_length=100),
        ),
    ]
