# Generated by Django 4.0.1 on 2023-01-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0010_student_internet_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_lab',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
    ]
