# Generated by Django 4.1.1 on 2022-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0010_rename_g_stats_faculty_wifi_g_stat_faculty_id_f_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_lab',
            name='l_stat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
