# Generated by Django 4.0.1 on 2023-01-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0011_faculty_lab_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='faculty_passreset',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='faculty_reports',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='maintain_record',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='passreset',
            name='adm',
            field=models.DateTimeField(null=True),
        ),
    ]
