# Generated by Django 4.1.3 on 2022-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0011_alter_faculty_id_f_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_id',
            name='f_sign',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
