# Generated by Django 4.0.4 on 2022-10-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0011_faculty_lab_l_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty_lab',
        ),
    ]
