# Generated by Django 4.1.1 on 2022-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0012_delete_faculty_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgsfe', models.CharField(max_length=100)),
                ('lidno', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='pics',
        ),
        migrations.RemoveField(
            model_name='register1',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='register1',
            name='idno',
        ),
        migrations.AddField(
            model_name='register1',
            name='gsfe',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='register1',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
