# Generated by Django 4.1.3 on 2022-12-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TupcSysApp', '0013_alter_faculty_id_f_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_id',
            name='f_sign',
        ),
    ]
